### ISSUE TITLE
The first condition inside the if sould have two = signs,

### ISSUE THREAD

**Issue by masecla22** [JamesHawkinss/reaction-bot#2]
https://github.com/JamesHawkinss/discord-archival-bot/blob/60b91e5e7e6edc18111956dbf363f3e823b670c5/index.js#L26

**Comment by masecla22** [comment]
The first condition inside the if sould have two = signs, otherwise it's just an assignement rather than a condition. As an edge case, try having two different types of reactions and having one of them which is not the checkmark go up to 2.

**Comment by JamesHawkinss** [comment]
Oh haha, nice spot! The other two conditions prevent this from being noticeable in actual use (usually) but I'll go ahead and change this now.
Thanks!

**Comment by JamesHawkinss** [comment]
All done 👍
